---
- name: Install list of packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nagios-nrpe-server
    - nagios-plugins

#- name: Install nrpe nagios packages
#  apt:
#      name: "{{ packages }}"
#      update_cache: yes
#      cache_valid_time: 3600
#  vars:
#      packages:
#          - nagios-nrpe-server
#          - nagios-plugins

- name: check if nagios check_cpu plugin exists
  stat:
      path: /usr/lib/nagios/plugins/check_cpu.sh
  register: check_cpu_file

- name: download and install nagios check_cpu plugin
  get_url:
      url: https://raw.githubusercontent.com/opinkerfi/nagios-plugins/master/check_cpu.sh/check_cpu.sh
      dest: /usr/lib/nagios/plugins/check_cpu.sh
      mode: "a+x"
  when: not check_cpu_file.stat.exists

- name: check if nagios check_service plugin exists
  stat:
      path: /usr/lib/nagios/plugins/check_service.sh
  register: check_service_file

- name: download and install nagios check_service plugin
  get_url:
      url: https://raw.githubusercontent.com/opinkerfi/nagios-plugins/master/check_service.sh/check_service.sh
      dest: /usr/lib/nagios/plugins/check_service.sh
      mode: "a+x"
  when: not check_service_file.stat.exists
