---
- name: Install nrpe nagios packages
  apt:
      name: "{{ packages }}"
  vars:
      packages:
          - nagios-nrpe-server
          - nagios-plugins

- name: check if nagios check_cpu plugin exists
  stat:
      path: /usr/lib/nagios/plugins/check_cpu.sh
  register: check_cpu_file

- name: download and install nagios check_cpu plugin
  get_url:
      url: https://raw.githubusercontent.com/opinkerfi/nagios-plugins/master/check_cpu.sh/check_cpu.sh
      dest: /usr/lib/nagios/plugins/check_cpu.sh
      mode: "a+x"
  when: not check_cpu_file.stat.exists
