---
- name: "Run tasks for Red Hat flavoured tasks"
  include: redhat_flavour.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: "Run tasks for Debian flavoured tasks"
  include: debian_flavour.yml
  when: ansible_facts['os_family'] == "Debian"
