---
- name: Display all variables/facts known for a host
  debug:
    var: ansible_virtualization_type
    verbosity: 1

- name: "Run tasks for Red Hat flavoured tasks"
  include: redhat_flavour.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: "Run tasks for Debian flavoured tasks"
  include: debian_flavour.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Copy nrpe.cfg to host
  template:
    src: templates/nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg
    mode: 0644
    owner: "{{ nagios_user[ansible_os_family] | first }}"
    group: "{{ nagios_group[ansible_os_family] | first }}"
  notify: Restart systemd service nrpe

- name: Copy ok-bundle.cfg to host
  template:
    src: templates/ok-bundle.cfg.j2
    dest: "{{ nrpe_dir[ansible_os_family] | first }}/ok-bundle.cfg"
    mode: 0644
    owner: "{{ nagios_user[ansible_os_family] | first }}"
    group: "{{ nagios_group[ansible_os_family] | first }}"
  notify: Restart systemd service nrpe

# X-Road plugin
- name: "Install plugin for x-road"
  include: nagios-plugin-x-road.yml
  when: "'xroad-securityserver-is' in ansible_facts.packages"
