---
# X-Road plugin install
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Nagios plugin for X-Road
  ansible.builtin.package:
    name: nagios-okplugin-check_xroad_token
    state: present
  when: "'xroad-securityserver-is' in ansible_facts.packages"
  notify: Restart systemd service nrpe

- name: Change the nrpe_t domain to permissive
  community.general.selinux_permissive:
    name: nrpe_t
    permissive: true

- name: allow nrpe to call sudo
  ansible.posix.seboolean:
    name: nagios_run_sudo
    state: yes
    persistent: yes
