---
- name: Install epel on CentOS
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install epel rpm on RHEL 7
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: Install epel rpm on RHEL 8
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

- name: Enable a RHSM repository for RHEL 7
  rhsm_repository:
    name: rhel-7-server-rpms
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: Add OK repository
  yum_repository:
    name: ok
    description: Opin Kerfi Public Repo
    enabled: true
    gpgcheck: false
    baseurl: http://opensource.is/repo/rhel$releasever/$basearch

- name: Add OK Testing repository
  yum_repository:
    name: ok-testing
    description: Opin Kerfi Public Repo - Testing
    enabled: true
    gpgcheck: false
    baseurl: http://opensource.is/repo/testing/rhel$releasever/$basearch

- name: Install a nrpe and dependencies
  yum:
    name:
      - nrpe
      - nrpe-selinux
      - bc
      - nagios-plugins-check_cpu
      - nagios-plugins-load
      - nagios-plugins-procs
      - nagios-plugins-swap
      - nagios-okconfig-nrpe
      - nagios-okplugin-check_firewall_active
    enablerepo: epel
    state: present

- name: check if nagios check_service plugin exists
  stat:
    path: "{{ nagios_plugins_dir[ansible_os_family]|first }}/check_service.sh"
  register: check_service_file

- name: download and install nagios check_service plugin
  get_url:
    url: https://raw.githubusercontent.com/opinkerfi/nagios-plugins/master/check_service.sh/check_service.sh
    dest: "{{ nagios_plugins_dir[ansible_os_family]|first }}/check_service.sh"
    mode: "a+x"
  when: not check_service_file.stat.exists
