---
- name: Install epel on CentOS
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install epel rpm on RHEL
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: Enable a RHSM repository for RHEL 7
  rhsm_repository:
    name: rhel-7-server-rpms
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: Add OK repository
  yum_repository:
    name: ok
    description: Opin Kerfi Public Repo
    enabled: true
    gpgcheck: false
    failovermethod: priority
    baseurl: http://opensource.is/repo/rhel$releasever/$basearch

- name: Add OK Testing repository
  yum_repository:
    name: ok-testing
    description: Opin Kerfi Public Repo - Testing
    enabled: true
    gpgcheck: false
    failovermethod: priority
    baseurl: http://opensource.is/repo/testing/rhel$releasever/$basearch

- name: Install a nrpe and dependencies
  yum:
    name:
      - nrpe
      - nagios-plugins-check_cpu
      - nagios-plugins-load
      - nagios-plugins-procs
      - nagios-plugins-swap
      - nagios-okconfig-nrpe
      - nagios-okplugin-check_firewall_active
      - redhat-lsb
    enablerepo: epel
    state: present
