---
# handlers file for okh_nagios_client

- name: Restart systemd service nrpe
  systemd:
      state: restarted
      enabled: true
      name: "{{ nrpe_service[ansible_os_family] | first }}"
  when: ansible_virtualization_type is not docker
